'use strict';

var currentSiteID = require('dw/system/Site').getCurrent().getID();
var File = require('dw/io/File');

const ALGOLIA_FILES_FOLDER = File.IMPEX + '/src/Algolia/';

const SNAPSHOT_PRODUCTS_FILE_NAME = ALGOLIA_FILES_FOLDER + currentSiteID + '_product.xml';
const TMP_SNAPSHOT_PRODUCTS_FILE_NAME = ALGOLIA_FILES_FOLDER + currentSiteID + '_product_tmp.xml';
const UPDATE_PRODUCTS_FILE_NAME = ALGOLIA_FILES_FOLDER + currentSiteID + '_product_update.xml';

const SNAPSHOT_CATEGORIES_FILE_NAME = ALGOLIA_FILES_FOLDER + currentSiteID + '_categories.xml';
const TMP_SNAPSHOT_CATEGORIES_FILE_NAME = ALGOLIA_FILES_FOLDER + currentSiteID + '_categories_tmp.xml';
const UPDATE_CATEGORIES_FILE_NAME = ALGOLIA_FILES_FOLDER + currentSiteID + '_categories_update.xml';

const ALGOLIA_LOG_FILE_NAME = '_lastUpdateLog.xml';
const ALGOLIA_LOG_FILE = ALGOLIA_FILES_FOLDER + currentSiteID + ALGOLIA_LOG_FILE_NAME;

// delta export job
const ALGOLIA_DELTA_EXPORT_BASE_FOLDER = File.IMPEX + '/src/platform/outbox/';
const ALGOLIA_DELTA_EXPORT_UPDATE_FILE_NAME = currentSiteID + '_product_update.xml';

module.exports = {
    ALGOLIA_FILES_FOLDER: ALGOLIA_FILES_FOLDER,
    SNAPSHOT_PRODUCTS_FILE_NAME: SNAPSHOT_PRODUCTS_FILE_NAME,
    TMP_SNAPSHOT_PRODUCTS_FILE_NAME: TMP_SNAPSHOT_PRODUCTS_FILE_NAME,
    UPDATE_PRODUCTS_FILE_NAME: UPDATE_PRODUCTS_FILE_NAME,

    SNAPSHOT_CATEGORIES_FILE_NAME: SNAPSHOT_CATEGORIES_FILE_NAME,
    TMP_SNAPSHOT_CATEGORIES_FILE_NAME: TMP_SNAPSHOT_CATEGORIES_FILE_NAME,
    UPDATE_CATEGORIES_FILE_NAME: UPDATE_CATEGORIES_FILE_NAME,

    ALGOLIA_LOG_FILE_NAME: ALGOLIA_LOG_FILE_NAME,
    ALGOLIA_LOG_FILE: ALGOLIA_LOG_FILE,

    ALGOLIA_DELTA_EXPORT_BASE_FOLDER: ALGOLIA_DELTA_EXPORT_BASE_FOLDER,
    ALGOLIA_DELTA_EXPORT_UPDATE_FILE_NAME: ALGOLIA_DELTA_EXPORT_UPDATE_FILE_NAME,
};
