name: Draft release
run-name: Draft release ${{ inputs.next_version }}

on:
  workflow_dispatch:
    inputs:
      next_version:
        required: true
        type: string
        description: 'Version name'

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: branch change and package version update
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout develop
          npm version --no-git-tag-version --no-commit-hooks ${{ inputs.next_version }}

      - name: Modify algoliaconfig file
        run: |
          sed -i 's/"version": ".*"/"version": "${{ inputs.next_version }}"/' cartridges/int_algolia/algoliaconfig.json

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update version to ${{ inputs.next_version }}"
          git push

      - name: Merge develop into master
        run: |
          set -e
          echo "Checking out develop branch..."
          git checkout develop
          git pull --ff-only
          echo "Switching to master branch..."
          git checkout master
          git pull --ff-only
          echo "Merging develop into master..."
          git merge --no-ff origin/develop
          echo "Pushing changes..."
          git push

      - name: Draft release
        run: gh release create $VERSION --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.next_version }}
